const mockEvents = {
  city: {
    id: 11201,
    city: 'Brooklyn',
    lat: 40.7,
    lon: -73.99,
    state: 'NY',
    country: 'us',
    zip: '11201',
    member_count: 40247
  },
  events: [
    {
      created: 1560297131000,
      duration: 7200000,
      id: 'swxdcryzlbjc',
      name: 'UXHQ Happy Hour',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566860400000,
      local_date: '2019-08-26',
      local_time: '19:00',
      updated: 1560297131000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 87,
      venue: {
        id: 22076222,
        name: 'Stitch Bar & Lounge',
        lat: 40.75393295288086,
        lon: -73.99150085449219,
        repinned: true,
        address_1: '247 W 37th St',
        city: 'New York',
        country: 'US',
        localized_country_name: 'USA'
      },
      group: {
        created: 1452013461000,
        name: 'User Experience HQ (NYC)',
        id: 19283289,
        join_mode: 'open',
        lat: 40.72999954223633,
        lon: -73.98999786376953,
        urlname: 'userexperiencehq',
        who: 'members',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/userexperiencehq/events/swxdcryzlbjc/',
      description:
        '<p>Do not miss a great opportunity to mingle and hang out with fellow UX professionals! Make connections, friends and have fun!</p> <p>The event is BYOD (B is for buy, D is for Drinks so please do NOT bring your own drinks to the bar :)</p> ',
      how_to_find_us: 'We will be near the bar',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1560297131000,
      duration: 7200000,
      id: 'swxdcryzmbfc',
      name: 'UXHQ Happy Hour',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1569279600000,
      local_date: '2019-09-23',
      local_time: '19:00',
      updated: 1560297131000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      venue: {
        id: 22076222,
        name: 'Stitch Bar & Lounge',
        lat: 40.75393295288086,
        lon: -73.99150085449219,
        repinned: true,
        address_1: '247 W 37th St',
        city: 'New York',
        country: 'US',
        localized_country_name: 'USA'
      },
      group: {
        created: 1452013461000,
        name: 'User Experience HQ (NYC)',
        id: 19283289,
        join_mode: 'open',
        lat: 40.72999954223633,
        lon: -73.98999786376953,
        urlname: 'userexperiencehq',
        who: 'members',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/userexperiencehq/events/swxdcryzmbfc/',
      description:
        '<p>Do not miss a great opportunity to mingle and hang out with fellow UX professionals! Make connections, friends and have fun!</p> <p>The event is BYOD (B is for buy, D is for Drinks so please do NOT bring your own drinks to the bar :)</p> ',
      how_to_find_us: 'We will be near the bar',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1553725718000,
      duration: 9000000,
      id: 'fnkgfryzlbqb',
      name:
        '⚡Hyperledger Fabric for the Enterprise - Privacy and Security Strategies⚡',
      rsvp_limit: 40,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566858600000,
      local_date: '2019-08-26',
      local_time: '18:30',
      updated: 1564509945000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 27,
      venue: {
        id: 24538509,
        name: 'WeWork Dumbo Heights',
        lat: 40.700862884521484,
        lon: -73.98747253417969,
        repinned: true,
        address_1: '81 Prospect St',
        city: 'Brooklyn',
        country: 'US',
        localized_country_name: 'USA',
        phone: '+16469789915'
      },
      group: {
        created: 1460157055000,
        name: 'NYC Blockchain Devs',
        id: 19817557,
        join_mode: 'open',
        lat: 40.689998626708984,
        lon: -74.01000213623047,
        urlname: 'nyc-blockchain-devs',
        who: 'Members',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/nyc-blockchain-devs/events/fnkgfryzlbqb/',
      description:
        '<p>The Flatiron School // Access Labs are proud to support the Ethereum Blockchain Devs Study Group. This is a regular gathering for Blockchain Devs of all levels to learn, present, work on in collaboration with one another or on solo projects in this fast-growing field. Our community is a welcoming space where any Ethereum and de-centralized ledger related question is fair game, be it beginner, intermediate, or advanced.</p> <p>------------------------<br/>AGENDA \u200d🎟️<br/>------------------------<br/>🎤 6:30pm - 7:00pm: General Blockchain Beginner Q&amp;A<br/>🎤 7:00pm - 8:45pm: IBM Intro, Privacy Demos, and Security Presentation<br/>\u200d🎤 7:20pm - 8:50pm: Q&amp;A<br/>🎤 8:50pm - 9:00pm: wrap up</p> <p>TODAY:<br/>Hyperledger Fabric (HLF) blockchain’s architecture was designed from the ground up to be highly extensible with plug and play modules in order to meet most business cases. The many permutations of these modules, also make it hard to decide what to use and how to configure them properly. In most cases this is not well documented, nor are the best practices easy to find, and hence seldom followed. This results in unsafe, buggy, and slow systems not worthy of what one expects of any enterprise application, blockchain none-withstanding!</p> <p>In this session, we will address the challenges of privacy and security by presenting the best patterns and methodologies, of how to implement enterprise grade HLF blockchain implementations. Further more we will cite real world examples – illustrated with diagrams, code-patterns and in some cases short demos or video segments.</p> <p>Get a head start with IBM Cloud and join via: ',
      how_to_find_us:
        'In Flatiron School/Access Labs 3rd floor: Please bring ID and sign in under Anthony Albertorio',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1563465693000,
      duration: 9000000,
      id: 'fnkgfryzmbvb',
      name:
        '⚡UMA: Intro to Decentralized Finance & Financial Derivatives on the Blockchain⚡',
      rsvp_limit: 40,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1568673000000,
      local_date: '2019-09-16',
      local_time: '18:30',
      updated: 1565651876000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 25,
      venue: {
        id: 24538509,
        name: 'WeWork Dumbo Heights',
        lat: 40.700862884521484,
        lon: -73.98747253417969,
        repinned: true,
        address_1: '81 Prospect St',
        city: 'Brooklyn',
        country: 'US',
        localized_country_name: 'USA',
        phone: '+16469789915'
      },
      group: {
        created: 1460157055000,
        name: 'NYC Blockchain Devs',
        id: 19817557,
        join_mode: 'open',
        lat: 40.689998626708984,
        lon: -74.01000213623047,
        urlname: 'nyc-blockchain-devs',
        who: 'Members',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/nyc-blockchain-devs/events/fnkgfryzmbvb/',
      description:
        '<p>The Flatiron School // Access Labs are proud to support the Ethereum Blockchain Devs Study Group. This is a regular gathering for Blockchain Devs of all levels to learn, present, work on in collaboration with one another or on solo projects in this fast-growing field. Our community is a welcoming space where any Ethereum and de-centralized ledger related question is fair game, be it beginner, intermediate, or advanced.</p> <p>------------------------<br/>AGENDA \u200d🎟️<br/>------------------------<br/>🎤 6:30pm -7:00pm Intro to #DeFi, or Decentralized Finance<br/>🎤 7:00 - 7:30pm: Intro to financial derivatives on the blockchain and demo of UMA’s infrastructure<br/>🎤 7:30pm -8:15pm: Workshop to create synthetic assets on testnet<br/>\u200d🎤 8:15pm - 8:30pm: Workshop to create synthetic assets on testnet<br/>🎤 8:30pm - 9:00pm: Q&amp;A</p> <p>Description:<br/>UMA is a decentralized financial contracts platform built to enable Universal Market Access. Our technology consists of two sets of infrastructure. The first is financial contract design patterns that use economic incentives alone to ensure payout, creating a non-recourse system for financial risk transfer. The second is a decentralized data verification mechanism that adds economic guarantees to blockchain oracles.</p> <p>This workshop will teach participants how to build best-in-class financial contracts on Ethereum that can support a wide array of DeFi use cases. Using concepts borrowed from fiat financial derivatives, participants will learn—with real, interactive examples—how to design and create their own decentralized financial contracts that are self-enforcing, permissionless and universally accessible. The discussion will highlight common pitfalls in building financial products on blockchains, and discuss security and mechanism design concerns. Participants will learn common design patterns to write contracts that can scale to support billions of dollars of economic activity.</p> <p>If you attend this session, you can expect to:<br/>Attain a basic understanding of the #DeFi movement and core concepts behind financial derivatives.<br/>Learn why financial derivatives are different on blockchains (Discussion and demonstration of security vulnerabilities in some existing designs).<br/>Understand common exploits and attack vectors for blockchain based derivatives.<br/>Practice best practices for creating secure synthetic derivatives (Audience can deploy contracts to testnet)</p> <p>To learn more:<br/>DM and/or follow us on Twitter @UMAprotocol<br/>Follow us on Medium<br/>Sign up for early access at www.umaproject.org<br/>Read our whitepaper / check out our GitHub<br/>------------------------<br/>CURRICULUM<br/>------------------------<br/>SEE FULL CURRICULUM HERE:<br/><a ',
      how_to_find_us:
        'In Flatiron School/Access Labs 3rd floor: Please bring ID and sign in under Anthony Albertorio',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1565057090000,
      duration: 7200000,
      id: '263765355',
      name: 'Build your first RestAPI with Golang',
      rsvp_limit: 120,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566426600000,
      local_date: '2019-08-21',
      local_time: '18:30',
      updated: 1566206527000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 87,
      venue: {
        id: 26152482,
        name: 'NYC Blockchain Center',
        lat: 40.741180419921875,
        lon: -73.99319458007812,
        repinned: true,
        address_1: '54 W 21st St',
        city: 'New York',
        country: 'us',
        localized_country_name: 'USA',
        zip: '10010',
        state: 'NY'
      },
      group: {
        created: 1402874789000,
        name: 'IBM Developer New York',
        id: 15104552,
        join_mode: 'open',
        lat: 40.72999954223633,
        lon: -73.98999786376953,
        urlname: 'ibmcodenyc',
        who: 'Coders',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/ibmcodenyc/events/263765355/',
      description:
        '<p>Golang is a language heavily used for web api building. What makes a good api? How can we build apis that are robust and extensible? Writing a good API is a evolving process.</p> <p>If you are coming to Go from a different language you might be used to using some framework for building REST APIs. Although that seems to increase developer productivity in the beginning, I feel like you loose a lot of visibility and flexibility because of the abstraction. The Go ecosystem favors libraries over frameworks. We will use a library to build our API. Using a library gives us the ability to easily change and modify our API.</p> <p>In this workshop we will take a data set and make an API out of it and learn some of the best practices in making a good API.</p> <p>Attendees can expect to learn:</p> <p>- How a REST API works<br/>- How to make an API<br/>- How to extend an API</p> <p>Pre-requisites</p> <p>- Basic understanding of Go and a Go runtime is useful.<br/>- Install go - <a ',
      how_to_find_us: 'Meet us on the 10th floor in suite 1001',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1565199654000,
      duration: 10800000,
      id: '263810587',
      name: 'Drupal NYC Meetup @ MongoDB - September 11',
      rsvp_limit: 125,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1568239200000,
      local_date: '2019-09-11',
      local_time: '18:00',
      rsvp_close_offset: 'PT31H',
      updated: 1565215199000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 28,
      venue: {
        id: 26131318,
        name: 'MongoDB',
        lat: 40.7619743347168,
        lon: -73.98435974121094,
        repinned: false,
        address_1: '1633 Broadway 38th floor',
        city: 'New York',
        country: 'us',
        localized_country_name: 'USA',
        zip: '10019',
        state: 'NY'
      },
      group: {
        created: 1306092694000,
        name: 'Drupal NYC',
        id: 1899751,
        join_mode: 'open',
        lat: 40.7599983215332,
        lon: -73.98999786376953,
        urlname: 'drupalnyc',
        who: 'Drupalers',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/drupalnyc/events/263810587/',
      description:
        "<p>Welcome to the Drupal NYC monthly meetup!</p> <p>Please join us on Wednesday, September 11th for our monthly Meetup for an evening of food, drinks, knowledge, and friendship at the HQ of our generous venue sponsor, MongoDB!</p> <p>All are welcome to attend the Drupal NYC Meetup. At each meetup there will be one or more lightning talks and presentations as well as opportunities for new and old Drupalers to network, socialize, and get their Drupal questions answered.</p> <p>You must enter your real name on the RSVP question (for building security) by 11am on Tuesday, September 10th or your RSVP will be removed. Check-in opens at 6pm sharp (please don't arrive earlier). We look forward to seeing you!</p> <p>Agenda<br/>• 6:00 - Check-in opens, socializing + pizza and drinks (generously sponsored by Pantheon)<br/>• 6:30 - Announcements<br/>• 6:45 - Who's hiring, who's looking?<br/>• 6:50 - Presentations!<br/>• 8:20 - Closing remarks, socializing + leftover pizza/drinks<br/>• 8:45 - After party (location TBD)</p> <p>==========</p> <p>Additional Presentations TBD</p> <p>Please volunteer to speak on any topic (or on a topic TBD and we will help find an appropriate topic), short or long. Organizers are happy to provide coaching for first-time speakers or those less comfortable speaking to a group. Links below.</p> <p>==========</p> <p>Have feedback for your volunteer organizers? We want to hear it: <a ",
      how_to_find_us:
        'Enter Paramount Plaza from Broadway between 50th and 51st streets. MongoDB is on the 38th floor. You must show your photo ID to security in the building lobby and also check-in on the 38th floor. Please arrive no earlier than 6PM.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1564700626000,
      duration: 7200000,
      id: '263658329',
      name: 'Panel: Excelling in Cross-Functional Teams (Partner Event)',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566424800000,
      local_date: '2019-08-21',
      local_time: '18:00',
      updated: 1565888144000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 35,
      venue: {
        id: 25293359,
        name: 'VTS',
        lat: 40.754310607910156,
        lon: -73.98625946044922,
        repinned: true,
        address_1: '119 West 40th Street',
        city: 'New York',
        country: 'US',
        localized_country_name: 'USA'
      },
      group: {
        created: 1484876702000,
        name: 'Build with Code - New York City',
        id: 21993357,
        join_mode: 'open',
        lat: 40.75,
        lon: -73.98999786376953,
        urlname: 'Build-with-Code-New-York',
        who: 'Engineers',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Build-with-Code-New-York/events/263658329/',
      description:
        "<p>VTS has graciously offered to sponsor this month's WiSE meetup! We'll get to hear from some of their prominent leaders about different roles within engineering teams. Whether it be QA or the product management track, there are many different and exciting careers that can contribute to building new products. This panel discussion will focus on how engineers work within different team contexts and provide empathy for non-engineering roles within tech.</p> <p>We created the Women in Software Engineering (WiSE) Speaker Series to highlight the accomplishments of successful women engineers, and to connect women aspiring to be software engineers to mentors and peers. These events occur each month and are open to all.</p> <p>Agenda -</p> <p>6:00pm - 6:30pm: Check-in - food and drinks will be available</p> <p>6:30pm - 7:30pm: Panel with Q&amp;A</p> <p>7:30pm - 8pm: Wrap up and networking</p> <p>Speakers -</p> <p>Becky Frost, QA Manager<br/>Becky is a passionate and analytical advocate of quality in every phase of product development.<br/>She loves enabling teams to deliver premium user-centered experiences no matter the context.<br/>From product to agency work, she is the happiest solving tough problems with curious and driven team members at her side.</p> <p>Jessie Daley, Senior Product Manager, Truva<br/>Jessie works on our newest product offering, truva as a Senior Product Manager. Jessie is hard at work doing research and working with the other members of team truva working to get this product in beta by the fall.</p> <p>Bianca Soliz, Senior Product Manager, BI<br/>Bianca is a Senior Product Manager for our business intelligence product, VTS BI. This was an extremely exciting launch we had last year and it has been extremely successful for us.</p> <p>Tania Abdollahi, Software Engineer, Truva<br/>Tania is a Software Engineer, currently on the Truva team. She is excited about delivering high quality software to solve interesting problems. She thrives in collaborative environments and enjoys advocating for engineering practices such as TDD and pairing.</p> <p>Where -</p> <p>VTS</p> <p>114 West 41st Street, 11th floor, New York, NY 10036</p> <p>--</p> <p>Looking forward to seeing you there!</p> ",
      how_to_find_us:
        'This meetup will take place at VTS at 114 West 41st Street in Midtown',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1565291487000,
      duration: 9000000,
      id: '263842387',
      name: 'Intro to JavaScript - Functions and Objects',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566426600000,
      local_date: '2019-08-21',
      local_time: '18:30',
      updated: 1565291489000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 65,
      venue: {
        id: 26022230,
        name: 'Codesmith',
        lat: 40.7183952331543,
        lon: -74.00334930419922,
        repinned: false,
        address_1: '68 White Street,',
        address_2: '5th Floor',
        city: 'New York',
        country: 'US',
        localized_country_name: 'USA'
      },
      group: {
        created: 1484876702000,
        name: 'Build with Code - New York City',
        id: 21993357,
        join_mode: 'open',
        lat: 40.75,
        lon: -73.98999786376953,
        urlname: 'Build-with-Code-New-York',
        who: 'Engineers',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Build-with-Code-New-York/events/263842387/',
      description:
        '<p>Join us at our New York City HQ in Tribeca to master the fundamentals of JavaScript. This workshop is designed specifically with beginners in mind! To get the full experience we recommend coming onsite, however a live-stream will be available if you’re unable to make it.<br/>&lt;br/&gt;&lt;br/&gt;<br/>This workshop will be a combination of live interactive lecture and pair programming through challenges! You will go under-the-hood of JavaScript, so you can confidently tackle new problems and work through blocks.<br/>&lt;br/&gt;&lt;br/&gt;<br/>During this workshop, we will cover: &lt;br/&gt;<br/>- What happens when our code runs in the browser? &lt;br/&gt;<br/>- A closer look at objects &lt;br/&gt;<br/>- Reusing our logic (declaring/invoking functions)<br/>&lt;br/&gt;&lt;br/&gt;<br/>Price: Always free!<br/>&lt;br/&gt;&lt;br/&gt;<br/>Transport Info: One block from: Canal St Station (N Q R W), Canal St Station (6), Canal St Station (J Z), and 4 blocks from Canal St Station (A C E)&lt;br/&gt;<br/>Online Info: Please join us for the online stream of the workshop here: ',
      how_to_find_us:
        'This meetup will take place at our HQ at 68 White St 5th floor in Tribeca and online stream: https://codesmith.io/event-signin/425?ol=t',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1565291656000,
      duration: 9000000,
      id: '263842453',
      name: 'JavaScript the Hard Parts: Callbacks & Higher Order Functions',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566513000000,
      local_date: '2019-08-22',
      local_time: '18:30',
      updated: 1566178841000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 51,
      venue: {
        id: 26022230,
        name: 'Codesmith',
        lat: 40.7183952331543,
        lon: -74.00334930419922,
        repinned: true,
        address_1: '68 White Street,',
        address_2: '5th Floor',
        city: 'New York',
        country: 'US',
        localized_country_name: 'USA'
      },
      group: {
        created: 1484876702000,
        name: 'Build with Code - New York City',
        id: 21993357,
        join_mode: 'open',
        lat: 40.75,
        lon: -73.98999786376953,
        urlname: 'Build-with-Code-New-York',
        who: 'Engineers',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Build-with-Code-New-York/events/263842453/',
      description:
        '<p>Join us at our New York City HQ in Tribeca to master JavaScript callbacks and higher order functions, followed by Codesmith drinks and networking! To get the full experience we recommend coming onsite, however a live-stream will be available if you’re unable to make it.</p> <p>This workshop will be a combination of live interactive lecture and pair programming through challenges, followed by networking and drinks! You will go under-the-hood of JavaScript, so you can confidently tackle new problems and work through blocks.</p> <p>During this workshop we will cover:</p> <p>- Building functions like map, reduce, and filter from scratch</p> <p>- Using higher order functions to keep code clean even if complex situations</p> <p>- How to diagram through higher order functions and callbacks scenarios</p> <p>Price: Always free!</p> <p>Transport Info: One block from: Canal St Station (N Q R W), Canal St Station (6), Canal St Station (J Z), and 4 blocks from Canal St Station (A C E)</p> <p>Online Info: Please join us for the online stream of the workshop here: ',
      how_to_find_us:
        'This meetup will take place at our HQ at 68 White St 5th floor in Tribeca and online stream: https://codesmith.io/event-signin/426?ol=t',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1564893848000,
      duration: 7200000,
      id: '263715018',
      name: 'Diverse Algorithms for Online Design Communities',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566513000000,
      local_date: '2019-08-22',
      local_time: '18:30',
      updated: 1566229705000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 22,
      venue: {
        id: 26347315,
        name: 'R-Lab',
        lat: 40.699867248535156,
        lon: -73.9771728515625,
        repinned: true,
        address_1: 'Mc Donough Ave',
        city: 'Brooklyn',
        country: 'us',
        localized_country_name: 'USA',
        zip: '11205',
        state: 'NY'
      },
      group: {
        created: 1368124862000,
        name: 'ACM New York City',
        id: 8417772,
        join_mode: 'open',
        lat: 40.720001220703125,
        lon: -74,
        urlname: 'ACM-NY',
        who: 'Peers',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/ACM-NY/events/263715018/',
      description:
        '<p>Welcome to our next meetup with Faez Ahmed, Ph.D., on the topic of forming diverse design teams to evaluate design ideas.</p> <p>Please be sure to provide your full name and email in order to gain access to the building using this Google Form: <a ',
      how_to_find_us: 'Location: Building 22, Gate: Sands St.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1546534570000,
      duration: 7200000,
      id: 'hjmgpqyzlbkc',
      name: 'Hack Night at Carbon Five NYC!',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566945000000,
      local_date: '2019-08-27',
      local_time: '18:30',
      updated: 1546534570000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 35,
      venue: {
        id: 25095240,
        name: 'Carbon Five NYC',
        lat: 40.72322463989258,
        lon: -74.00112915039062,
        repinned: true,
        address_1: '65 Greene St 4th floor',
        city: 'New York',
        country: 'us',
        localized_country_name: 'USA',
        zip: '',
        state: 'NY'
      },
      group: {
        created: 1459971492000,
        name: 'Carbon Five NYC Hack Nights',
        id: 19808875,
        join_mode: 'open',
        lat: 40.720001220703125,
        lon: -74,
        urlname: 'Carbon-Five-NYC-Hack-Nights',
        who: 'Hackers',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link:
        'https://www.meetup.com/Carbon-Five-NYC-Hack-Nights/events/hjmgpqyzlbkc/',
      description:
        "<p>Come join us the last Tuesday of every month for Hack Night, hosted at our NYC office in Soho!</p> <p>Carbon Five hosts a regular hack night for developers and designers who enjoy getting together and coding for a few hours on their own projects. Our hack nights are a low-key, demo-free event, created to unite talented folks who enjoy building stuff :)</p> <p>We'll be doing a quick  ",
      how_to_find_us:
        'Head to the 4th floor! The elevator is manual and pretty old so please use the stairs :)',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      local_time: '18:00',
      local_date: '2019-09-25',
      link: 'https://www.meetup.com/SemioticsWeb/events/263703131/',
      visibility: 'public_limited',
      group: {
        created: 1333752623000,
        name: 'Semiotics Web',
        id: 3620962,
        join_mode: 'approval',
        lat: 40.75,
        lon: -73.98999786376953,
        urlname: 'SemioticsWeb',
        who: 'semioticians',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      waitlist_count: 0,
      yes_rsvp_count: 16,
      duration: 10800000,
      time: 1569448800000,
      utc_offset: -14400000,
      name:
        'Micro-Graph Visualization, On Language and Value in American English, and TBA',
      id: '263703131'
    },
    {
      created: 1565365150000,
      duration: 7200000,
      id: '263867394',
      name: 'Astoria Tech Meetup #11 - ',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1567031400000,
      local_date: '2019-08-28',
      local_time: '18:30',
      updated: 1565485225000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 26,
      venue: {
        id: 26459787,
        name: 'The Strand Smokehouse',
        lat: 40.763057708740234,
        lon: -73.92739868164062,
        repinned: true,
        address_1: '25-27 Broadway',
        city: 'Astoria',
        country: 'us',
        localized_country_name: 'USA',
        zip: '11106',
        state: 'NY'
      },
      group: {
        created: 1395854339000,
        name: 'Astoria Tech Meetup',
        id: 13565062,
        join_mode: 'open',
        lat: 40.7599983215332,
        lon: -73.91000366210938,
        urlname: 'Astoria-Tech-Meetup',
        who: 'Members',
        localized_location: 'Astoria, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Astoria-Tech-Meetup/events/263867394/',
      description:
        "<p>Hello fellow Astorians!</p> <p>Our 11th meetup is coming up at The Strand Smokehouse, right by the Broadway station. So whether you're in tech or just interested, come on by.</p> <p>This month we're welcoming Peter Berg, resident of Astoria and founder of Forward who will be giving a talk titled, ",
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1563221466000,
      duration: 7200000,
      id: '263176736',
      name: 'AngularNYC August: ',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566338400000,
      local_date: '2019-08-20',
      local_time: '18:00',
      updated: 1564059457000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 200,
      venue: {
        id: 25931550,
        name: 'Capital One',
        lat: 40.739662170410156,
        lon: -73.99227905273438,
        repinned: true,
        address_1: '11 West 19 Street',
        address_2: '3rd Floor',
        city: 'New York',
        country: 'us',
        localized_country_name: 'USA',
        zip: '10011',
        state: 'ny'
      },
      group: {
        created: 1335027647000,
        name: 'Angular NYC',
        id: 3714032,
        join_mode: 'open',
        lat: 40.7400016784668,
        lon: -74,
        urlname: 'AngularNYC',
        who: 'Angels',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/AngularNYC/events/263176736/',
      description:
        '<p>Join us in August for a chill, rest and Angular Talks!</p> <p>🕒 6:00 - Chill<br/>🕒 6:30 - Intros</p> <p>🕒 6:45 - Naomi Meyer<br/>🎤 Building Angular Apps with Internationalization (I18N) in Mind</p> <p>At Adobe we build products for the world, this talk with provide a high level overview of internationalization (i18n), globalization (g11n), and localization (l11n) learnings. Why these are important and how to implement in design, UX, and within the codebase - using Angular code examples and 3rd party library recommendations.</p> <p>About Naomi Meyer: Naomi currently works as a Software Development Engineer at Adobe in New York City, where she is the product champion for internationalization (i18n) on her team. Before writing JavaScript full time, Naomi worked teaching English as a foreign language in local classrooms across Asia and West Africa. She is passionate about developing with diversity, inclusion, and internationalization (i18n) in mind, and enjoys hiking and riding bikes on the weekends.</p> <p>🕒 7:10 - Break</p> <p>🕒 7:20 - Nir Kaufman<br/>🎤 Create your first Angular library</p> <p>In this talk, I will guide you through the process of creating an Angular library from scratch using the Angular CLI. You will learn how to set up a project correctly, how to configure your library, and how to generate a sample project to test it.</p> <p>🕒 8:10<br/>🍻☕️ Post-event hangout:</p> <p>Rye House<br/>11 West 17th Street, New York, NY 10011</p> <p>----------------------------------------------</p> <p>▶ If you’re interested in giving a talk, please let us know! Speakers of all levels and backgrounds are welcome, and we have experienced mentors who can help you prepare your talk!</p> <p>Check out our Speaker FAQ:  ',
      how_to_find_us: 'Find us at the reception on the first floor! ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '18:30',
      local_date: '2019-10-15',
      link:
        'https://www.meetup.com/NYC-Apache-Lucene-Solr-Meetup/events/258293079/',
      visibility: 'public_limited',
      group: {
        created: 1246465233000,
        name: 'NYC Apache Lucene/Solr Meetup',
        id: 1482573,
        join_mode: 'open',
        lat: 40.7599983215332,
        lon: -73.98999786376953,
        urlname: 'NYC-Apache-Lucene-Solr-Meetup',
        who: 'Luceners',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      waitlist_count: 0,
      yes_rsvp_count: 34,
      duration: 7200000,
      time: 1571178600000,
      utc_offset: -14400000,
      name: 'Understanding your Users through Query Log Analysis',
      id: '258293079'
    },
    {
      local_time: '18:30',
      local_date: '2019-11-07',
      link:
        'https://www.meetup.com/NYC-Apache-Lucene-Solr-Meetup/events/258125140/',
      visibility: 'public_limited',
      group: {
        created: 1246465233000,
        name: 'NYC Apache Lucene/Solr Meetup',
        id: 1482573,
        join_mode: 'open',
        lat: 40.7599983215332,
        lon: -73.98999786376953,
        urlname: 'NYC-Apache-Lucene-Solr-Meetup',
        who: 'Luceners',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      waitlist_count: 0,
      yes_rsvp_count: 18,
      duration: 7200000,
      time: 1573169400000,
      utc_offset: -18000000,
      name: 'Search and AI Powered Sidekick',
      id: '258125140'
    },
    {
      created: 1564781905000,
      duration: 9000000,
      id: '263684543',
      name: 'Reactive Programming for the Impatient Developer',
      rsvp_limit: 150,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1567031400000,
      local_date: '2019-08-28',
      local_time: '18:30',
      updated: 1565282202000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 24,
      venue: {
        id: 26152482,
        name: 'NYC Blockchain Center',
        lat: 40.741180419921875,
        lon: -73.99319458007812,
        repinned: true,
        address_1: '54 W 21st St',
        city: 'New York',
        country: 'us',
        localized_country_name: 'USA',
        zip: '10010',
        state: 'NY'
      },
      group: {
        created: 1402874789000,
        name: 'IBM Developer New York',
        id: 15104552,
        join_mode: 'open',
        lat: 40.72999954223633,
        lon: -73.98999786376953,
        urlname: 'ibmcodenyc',
        who: 'Coders',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/ibmcodenyc/events/263684543/',
      description:
        '<p>As Java is an object-oriented language that inherently supports the imperative programming style; asynchronicity presents a challenge that can turn one’s code into a nightmare. One way to deal with the complexity of asynchronicity is to introduce reactivity onto the coding level (reactive functional programming), and/or to handle it on the design and architecture level (reactive systems design).</p> <p>This workshop will introduce you to the principles that drive the movement towards Reactive Systems. We will focus primarily on Reactive Functional Programming, where we will conduct a progressive hands on coding session that will teach you how to start using Java Streams and RxJava and examples of how you might use these techniques in your software applications today.</p> <p>Pre-requisites<br/>Since we will be covering Java you should already be comfortable with running Java, compiling it ( Javac ) And it’s common build tools like Maven or Gradle</p> <p>While it is not necessary for the attendees to have experience in reactive style of programming, an understanding of and some basic experience on the traditional imperative programming style is highly recommended.</p> <p>Please bring a laptop.</p> <p>Agenda:</p> <p>630pm - doors open, pizza, drinks, &amp; networking<br/>7-815pm - workshop<br/>[masked]pm - Q&amp;A/networking<br/>9pm - doors close</p> <p>Get a head start with IBM Cloud, sign up via: ',
      how_to_find_us: 'Join us at suite 1001 on the 10th floor.',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      local_time: '18:30',
      local_date: '2019-09-04',
      link:
        'https://www.meetup.com/NYC-Apache-Lucene-Solr-Meetup/events/258124619/',
      visibility: 'public_limited',
      group: {
        created: 1246465233000,
        name: 'NYC Apache Lucene/Solr Meetup',
        id: 1482573,
        join_mode: 'open',
        lat: 40.7599983215332,
        lon: -73.98999786376953,
        urlname: 'NYC-Apache-Lucene-Solr-Meetup',
        who: 'Luceners',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      waitlist_count: 0,
      yes_rsvp_count: 32,
      duration: 7200000,
      time: 1567636200000,
      utc_offset: -14400000,
      name:
        'Lessons from the Field: Common Mistakes Made Deploying a Search App with Fusion',
      id: '258124619'
    },
    {
      local_time: '18:00',
      local_date: '2019-10-23',
      link: 'https://www.meetup.com/SemioticsWeb/events/263704222/',
      visibility: 'public_limited',
      group: {
        created: 1333752623000,
        name: 'Semiotics Web',
        id: 3620962,
        join_mode: 'approval',
        lat: 40.75,
        lon: -73.98999786376953,
        urlname: 'SemioticsWeb',
        who: 'semioticians',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      waitlist_count: 0,
      yes_rsvp_count: 12,
      duration: 10800000,
      time: 1571868000000,
      utc_offset: -14400000,
      name: 'A Practical Workshop on Semiospheres',
      id: '263704222'
    },
    {
      created: 1564505926000,
      duration: 5400000,
      id: '263587792',
      name: 'How to use Scala Effectively',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1567638000000,
      local_date: '2019-09-04',
      local_time: '19:00',
      updated: 1565580022000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 49,
      venue: {
        id: 26565861,
        name: '101 Hudson St',
        lat: 40.71607208251953,
        lon: -74.03506469726562,
        repinned: true,
        address_1: '101 Hudson St',
        city: 'Jersey City',
        country: 'us',
        localized_country_name: 'USA',
        zip: '07302',
        state: 'NJ'
      },
      group: {
        created: 1234036064000,
        name: 'ny-scala',
        id: 1377720,
        join_mode: 'open',
        lat: 40.720001220703125,
        lon: -74,
        urlname: 'ny-scala',
        who: 'Scala Types',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/ny-scala/events/263587792/',
      description:
        "<p>It's time for another talk at ny-scala! This time, our speaker is Benjamin Erichsen. Ben's company, William Hill, will host us and serve refreshments at their office in Exchange Place. As usual, doors will open at 6:30pm, and we'll get started at 7:00pm.</p> <p>Description<br/>================<br/>Scala is a language that has an immense feature set, including both functional and OOP concepts. It takes a lot of thought to figure out how to best utilize the language for successful software development. We are going to delve into a little history of FP and OOP, and then analyze some scala functionality to see how we can use the language optimally. We are going to objectively look at the functional and OOP paradigms to see what combination of them makes sense to use. I guarantee you that whether you are a newcomer to programming or a seasoned developer, there will be a wealth of information (and quotes!) for you to apply to your craft.</p> <p>About Benjamin<br/>================<br/>Since I have graduated from the University of Michigan with a degree in Computer Science, I have developed in C, C++, C# and Scala, in various domains such as transportation planning, banking and gambling. I have read many books on software development, completed online courses and attended many meetup groups. I have written down everything I have learned about software development and I consistently review it to improve my craft.</p> <p>About William Hill<br/>================<br/>William Hill, The Home of Betting, is one of the world’s leading betting and gaming companies, employing more than 17,000 people worldwide. William Hill is the first British bookmaker to be licensed in Nevada and has entered the U.S. market through acquisitions of American Wagering Inc., Brandywine Bookmaking LLC and Club Cal Neva sportsbooks, giving it 100 sports betting locations across Nevada. In addition, William Hill serves as the exclusive risk manager for the State of Delaware’s Sports Lottery.</p> ",
      how_to_find_us:
        'We are on floor 27. You must take the 2nd set of elevators, not the first. Please check in with the doorman when arriving',
      visibility: 'public',
      member_pay_fee: false
    }
  ]
};

export { mockEvents };
